apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-episode-05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-episode-05
  template:
    metadata:
      labels:
        app: frontend-episode-05
    spec:
      containers:
      - name: frontend
        image: matishaikh77/frontend_image5:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-episode-05
spec:
  type: NodePort
  selector:
    app: frontend-episode-05
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80